- name: Create Jenkins Jobs
  hosts: all
  connection: local
  tasks:
    - name: Create a jenkins job using basic authentication
      community.general.jenkins_job:
        config: "{{ lookup('file', 'templates/test.xml') }}"
        name: test-create-from-ansible
        password: admin
        url: http://localhost:8080
        user: admin