sjobs:
  - { git_repo_url: https://github.com/peasannaakkalareddy/roboshop-terraform.git, job_name: roboshop-terraform, file_name: Jenkinsfile }
  - { git_repo_url: https://github.com/peasannaakkalareddy/roboshop-ansible.git, job_name: roboshop-ansible, file_name: Jenkinsfile }
  - { git_repo_url: https://github.com/peasannaakkalareddy/aws-ssm-parameter-store.git, job_name: ssm-parameters, file_name: Jenkinsfile }
  - { git_repo_url: https://github.com/peasannaakkalareddy/aws-ssm-parameter-store.git, job_name: aws-ssm-ps-docker, file_name: Jenkinsfile-ps }
  - { git_repo_url: https://github.com/peasannaakkalareddy/roboshop-helm.git, job_name: roboshop-helm, file_name: Jenkinsfile }
  - { git_repo_url: https://github.com/peasannaakkalareddy/schema-loader.git, job_name: schema-loader, file_name: Jenkinsfile }


mjobs:
  - { git_repo_url: https://github.com/peasannaakkalareddy/cart.git, job_name: cart }
  - { git_repo_url: https://github.com/peasannaakkalareddy/user.git, job_name: user }
  - { git_repo_url: https://github.com/peasannaakkalareddy/catalogue.git, job_name: catalogue }
  - { git_repo_url: https://github.com/peasannaakkalareddy/shipping.git, job_name: shipping }
  - { git_repo_url: https://github.com/peasannaakkalareddy/payment.git, job_name: payment }
  - { git_repo_url: https://github.com/peasannaakkalareddy/frontend.git, job_name: frontend }


